# Generated by Django 5.2.15 on 2026-07-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistprofile',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
