# Generated by Django 5.2.15 on 2026-07-04 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_medicalhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('body_part', models.CharField(choices=[('shoulder', 'Shoulder'), ('knee', 'Knee'), ('elbow', 'Elbow'), ('hip', 'Hip'), ('spine', 'Spine'), ('ankle', 'Ankle'), ('full_body', 'Full Body')], max_length=20)),
                ('target_angle_min', models.FloatField()),
                ('target_angle_max', models.FloatField()),
                ('default_reps', models.IntegerField(default=10)),
                ('default_sets', models.IntegerField(default=3)),
                ('demo_video', models.FileField(blank=True, null=True, upload_to='exercise_demos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='exercise_thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExercisePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('goal', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_plans', to='myapp.userprofile')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to='myapp.therapistprofile')),
            ],
        ),
    ]
