# Generated by Django 5.2.15 on 2026-07-05 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_exercise_exerciseplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisePlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescribed_sets', models.IntegerField(default=3)),
                ('prescribed_reps', models.IntegerField(default=10)),
                ('frequency_per_week', models.IntegerField(default=3)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='myapp.exercise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.exerciseplan')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('aborted', 'Aborted')], default='in_progress', max_length=20)),
                ('recorded_video', models.FileField(blank=True, null=True, upload_to='session_recordings/')),
                ('completed_reps', models.IntegerField(default=0)),
                ('completed_sets', models.IntegerField(default=0)),
                ('avg_accuracy', models.FloatField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('started_date', models.DateTimeField(auto_now_add=True)),
                ('ended_date', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='myapp.userprofile')),
                ('plan_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='myapp.exerciseplanitem')),
            ],
        ),
    ]
