# Generated by Django 5.2.15 on 2026-07-05 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_exerciseplanitem_exercisesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0)),
                ('posture_feedback', models.TextField(blank=True, null=True)),
                ('repetition_accuracy', models.FloatField(default=0)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('flagged_for_review', models.BooleanField(default=False)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('therapist_comments', models.TextField(blank=True, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to='myapp.therapistprofile')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='myapp.exercisesession')),
            ],
        ),
        migrations.CreateModel(
            name='PoseFrameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('timestamp_ms', models.IntegerField()),
                ('joint_angle', models.FloatField()),
                ('posture_accuracy', models.FloatField()),
                ('is_rep_complete', models.BooleanField(default=False)),
                ('landmarks_json', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_logs', to='myapp.exercisesession')),
            ],
        ),
    ]
